# -*- coding: utf-8 -*-
"""Convert (.heic) to (.jpg).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11xNC_jC56uSUG-hilWbkP4CxEIZ7dVdT
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install Pillow

"""# **Convert .heic to .jpg**"""

!pip install pyheif

from PIL import Image
import pyheif

def convert_image(input_path, output_path):
    try:
        if input_path.lower().endswith('.heic'):
            # Convert HEIC to JPEG
            heif_file = pyheif.read(input_path)
            image = Image.frombytes(
                heif_file.mode,
                heif_file.size,
                heif_file.data,
                "raw",
                heif_file.mode,
                heif_file.stride,
            )
        else:
            # Open the image using Pillow
            image = Image.open(input_path)

        # Save the image as JPEG
        image.save(output_path, "JPEG")
        print(f"Converted: {input_path} -> {output_path}")
    except Exception as e:
        print(f"Error converting {input_path}: {str(e)}")

import os

input_folder = "/content/drive/MyDrive/folder"
output_folder = "/content/drive/MyDrive/new"

# Create the output folder if it doesn't exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for filename in os.listdir(input_folder):
    if filename.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.heic')):
        input_path = os.path.join(input_folder, filename)
        output_path = os.path.join(output_folder, filename.replace('.heic', '.jpg'))  # Replace .heic with .jpg
        convert_image(input_path, output_path)