# -*- coding: utf-8 -*-
"""Count total number of images in a class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FSvqhpz8BLij_Ml9nf55fUh8Y0ej4EqS
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install Pillow

"""# **Count total number of images in a class**"""

dataset_dir = '/content/drive/MyDrive/Dataset/class1'

# Initialize a count variable
image_count = 0

# Iterate through files in the directory
for filename in os.listdir(dataset_dir):
    if filename.endswith(('.jpg', '.jpeg', '.png', '.bmp', '.heic','.HEIC')):
        image_count += 1

print(f"Total number of images in the dataset: {image_count}")

