# -*- coding: utf-8 -*-
"""Marge classes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aREcXPAqZkS8sdXNy8SeIXbDVWd5vmHe
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install Pillow

"""# **Marge classes**"""

import os
import shutil

def merge_folders(root_directory, output_folder):
    # Create the output folder if it doesn't exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for folder_name in sorted(os.listdir(root_directory)):
        folder_path = os.path.join(root_directory, folder_name)
        if os.path.isdir(folder_path):
            copy_images_from_folder(folder_path, output_folder)

def copy_images_from_folder(source_folder, output_folder):
    image_extensions = ['.jpg', '.jpeg', '.png', '.gif', '.bmp']  # Add more extensions if needed

    for filename in sorted(os.listdir(source_folder)):
        if filename.lower().endswith(tuple(image_extensions)):
            source_path = os.path.join(source_folder, filename)
            output_path = os.path.join(output_folder, filename)
            # Check if the file exists in the output folder to avoid overwriting
            if not os.path.exists(output_path):
                shutil.copy2(source_path, output_path)
                print(f"Copied: {filename} to {output_folder}")

if __name__ == "__main__":
    root_directory = "/content/drive/MyDrive/Preprocessing/train"  # Replace with the path to your root directory containing image folders
    output_folder = "/content/drive/MyDrive/Preprocessing/yolo/data/train"  # Replace with the path to the new output folder

    merge_folders(root_directory, output_folder)