# -*- coding: utf-8 -*-
"""RGB Image Preprocess.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M6ybF8BKXqrqoqtJIj4WYuUMfiemS35Z
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install Pillow

"""# **Image Preprocess**"""

import os
import cv2

def process_image(input_path, output_path):
    # Load the image
    image = cv2.imread(input_path)

    # Adjust brightness and contrast
    brightness = 4
    contrast = 1.1
    image = cv2.convertScaleAbs(image, alpha=contrast, beta=brightness)


    # Apply sharpening
    image = cv2.GaussianBlur(image, (0, 0), 3)
    image = cv2.addWeighted(image, 1.6, image, -0.5, 0)

    # Save the processed image
    cv2.imwrite(output_path, image)

def process_images_in_folder(input_folder, output_folder):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for filename in os.listdir(input_folder):
        if filename.endswith(('.jpg', '.jpeg', '.png', '.bmp')):
            input_path = os.path.join(input_folder, filename)
            output_path = os.path.join(output_folder, filename)
            process_image(input_path, output_path)


if __name__ == "__main__":
    input_folder = "/content/drive/MyDrive/Dataset/Class1"  # Replace with your input folder path
    output_folder = "/content/drive/MyDrive/Preprocessing/Class1"  # Replace with your output folder path
    process_images_in_folder(input_folder, output_folder)

import os
import cv2

def process_image(input_path, output_path):
    # Load the image
    image = cv2.imread(input_path)

    # Adjust brightness and contrast
    brightness = 4
    contrast = 1.1
    image = cv2.convertScaleAbs(image, alpha=contrast, beta=brightness)


    # Apply sharpening
    image = cv2.GaussianBlur(image, (0, 0), 3)
    image = cv2.addWeighted(image, 1.6, image, -0.5, 0)

    # Save the processed image
    cv2.imwrite(output_path, image)

def process_images_in_folder(input_folder, output_folder):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    for filename in os.listdir(input_folder):
        if filename.endswith(('.jpg', '.jpeg', '.png', '.bmp')):
            input_path = os.path.join(input_folder, filename)
            output_path = os.path.join(output_folder, filename)
            process_image(input_path, output_path)


if __name__ == "__main__":
    input_folder = "/content/drive/MyDrive/Dataset/Class2"  # Replace with your input folder path
    output_folder = "/content/drive/MyDrive/Preprocessing/Class2"  # Replace with your output folder path
    process_images_in_folder(input_folder, output_folder)