# -*- coding: utf-8 -*-
"""Show image.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/146BIqwwd3Xgqg2fpSXnTFP6UnCxluskG
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install Pillow

"""# **Show image**"""

import cv2
from matplotlib import pyplot as plt

# Load the images
before_image = cv2.imread('/content/drive/MyDrive/Dataset/Cook_house_waste/image1.jpg')
after_image = cv2.imread('/content/drive/MyDrive/Preprocessing/Cook_house_waste/image1.jpg')

# Convert BGR images to RGB (OpenCV uses BGR by default)
before_image = cv2.cvtColor(before_image, cv2.COLOR_BGR2RGB)
after_image = cv2.cvtColor(after_image, cv2.COLOR_BGR2RGB)

# Plotting the images side by side
fig, axes = plt.subplots(1, 2, figsize=(12, 6))

axes[0].imshow(before_image)
axes[0].set_title('Before Image')

axes[1].imshow(after_image)
axes[1].set_title('After Image')

# Remove axis ticks
for ax in axes:
    ax.axis('off')

plt.show()